### ISSUE TITLE
hello,i have some questions,thanks

### ISSUE THREAD

**Issue by qinxiaotie** [FCYtheFreeman/MDD_sMRI_classification_PyTorch#1]
Hello, I also do imaging machine learning. I am interested in your project MDD_sMRI_classification_PyTorch-master, but I have a few questions that I hope to get your answers.

**Comment by qinxiaotie** [comment]
We can learn from each other, and at the same time, I can also share some video learning materials on MRI, such as gretna, PANDA, bainnet viewer, etc.  thank you!

**Comment by FCYtheFreeman** [comment]
> Hello, I also do imaging machine learning. I am interested in your project MDD_sMRI_classification_PyTorch-master, but I have a few questions that I hope to get your answers. How can I get in touch with you? My qq is 40444062, Thank you!

Hi, sorry for the late reply, haven't check it for a long time... you can send me email or just ask your question here, I'll reply ASAP.

**Comment by FCYtheFreeman** [comment]
> We can learn from each other, and at the same time, I can also share some video learning materials on MRI, such as gretna, PANDA, bainnet viewer, etc.  thank you!

Haha, thank you. I've used gretna and brainnet viewer for fMRI data before, but right now I'm more focusing on deep learning staff.

**Comment by qinxiaotie** [comment]
您好！请问您的邮箱是多少呢？期待回复，多谢哈！

**Comment by qinxiaotie** [comment]
您好！请问您的邮箱多少啊？

**Comment by FCYtheFreeman** [comment]
> 您好！请问您的邮箱多少啊？

直接提Issues吧，我会在这里回答。

**Comment by qinxiaotie** [comment]
您好啊！我的问题稍有点多，能加个QQ么？谢谢谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Freeman"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 中午11:06
收件人:&nbsp;"FCYtheFreeman/MDD_sMRI_classification_PyTorch"<MDD_sMRI_classification_PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"秦小铁"<85661336@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [FCYtheFreeman/MDD_sMRI_classification_PyTorch] hello,i have some questions,thanks (#1)





  
您好！请问您的邮箱多少啊？
  
直接提Issues吧，我会在这里回答。

**Comment by qinxiaotie** [comment]
您好啊！我的问题稍有点多，能加个QQ么？谢谢谢谢您！
我的是：40444062




------------------ 原始邮件 ------------------
发件人:&nbsp;"Freeman"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 中午11:06
收件人:&nbsp;"FCYtheFreeman/MDD_sMRI_classification_PyTorch"<MDD_sMRI_classification_PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"秦小铁"<85661336@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [FCYtheFreeman/MDD_sMRI_classification_PyTorch] hello,i have some questions,thanks (#1)





  
您好！请问您的邮箱多少啊？
  
直接提Issues吧，我会在这里回答。

**Comment by qinxiaotie** [comment]
from train import train_epochlabels = torch.LongTensor(labels).cuda(async = True)

Traceback (most recent call last):   File "E:/MDD_sMRI_classification_PyTorch-master/MDD_sMRI_classification_PyTorch-master/main.py", line 11, in <module&gt;     from train import train_epoch   File "E:\MDD_sMRI_classification_PyTorch-master\MDD_sMRI_classification_PyTorch-master\train.py", line 27     labels = torch.LongTensor(labels).cuda(async = True)                                                ^ SyntaxError: invalid syntax Process finished with exit code 1
您好！我运行main.py以后，上面两个地方报错，请问您用的python哪个版本写的代码哈？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Freeman"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 中午11:06
收件人:&nbsp;"FCYtheFreeman/MDD_sMRI_classification_PyTorch"<MDD_sMRI_classification_PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"秦小铁"<85661336@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [FCYtheFreeman/MDD_sMRI_classification_PyTorch] hello,i have some questions,thanks (#1)





 
Closed #1.

**Comment by qinxiaotie** [comment]
我这里有核磁各方面的视频学习资料，很多很多，如果您乐意，都可以分享给你哈。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Freeman"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 中午11:06
收件人:&nbsp;"FCYtheFreeman/MDD_sMRI_classification_PyTorch"<MDD_sMRI_classification_PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"秦小铁"<85661336@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [FCYtheFreeman/MDD_sMRI_classification_PyTorch] hello,i have some questions,thanks (#1)





 
Closed #1.
