### ISSUE TITLE
cuda?

### ISSUE THREAD

**Issue by stu5** [FCYtheFreeman/MDD_sMRI_classification_PyTorch#2]
if  I do not have cuda,I can run this code?

**Comment by FCYtheFreeman** [comment]
> if I do not have cuda,I can run this code?
No

**Comment by stu5** [comment]
I see that MRI image classifiers either convert to png or classify directly in the NII, which of these two methods do you think is more accurate?

**Comment by FCYtheFreeman** [comment]
> I see that MRI image classifiers either convert to png or classify directly in the NII, which of these two methods do you think is more accurate?

3D MRI data cannot convert to png directly, unless you want to convert each slice of them. I used 3D networks in this repo, so I had to feed them 3D data. And I think it doesn't matter whether you convert NII data to png if you use 2D network, the accurates should be the same.
